name: Docker Image CI

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/ztig3r/${{ inputs.project_name }}:latest
    
    - name: Push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --tag ghcr.io/ztig3r/${{ inputs.project_name }}:latest \
          .
